---
title: "pivot_lobsters"
author: "Henrik Gustafsson"
date: "7/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## attach libraries
library(tidyverse)
library(readxl)
library(here)
library(skimr) # install.packages('skimr')
library(kableExtra) # install.packages('kableExtra')

## read in data
lobsters <- read_xlsx(here("data/lobsters.xlsx"), skip=4)

```



# explore data
skimr::skim(lobsters)


lobsters %>%
  group_by(year) %>%
  summarize(count_by_year = n())

lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear =  n())

lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear =  n(),
            mean_size_mm = mean(size_mm))


remove NAs first before calculating the average:

lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear =  n(), 
            mean_size_mm = mean(size_mm, na.rm=TRUE), 
            sd_size_mm = sd(size_mm, na.rm=TRUE))


siteyear_summary <- lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear =  n(), 
            mean_size_mm = mean(size_mm, na.rm = TRUE), 
            sd_size_mm = sd(size_mm, na.rm = TRUE))


## make a table with our new variable
siteyear_summary %>%
  kable()
  


There are `r nrow(lobsters)` total lobsters included in this report.




siteyear_summary <- lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear =  n(), 
            mean_size_mm = mean(size_mm, na.rm = TRUE), 
            sd_size_mm = sd(size_mm, na.rm = TRUE), 
            median_size_mm = median(size_mm, na.rm = TRUE))

## `summarise()` regrouping output by 'site' (override with `.groups` argument)

## a ggplot option:
ggplot(data = siteyear_summary, aes(x = year, y = median_size_mm, color = site)) +
  geom_line()
  
  
ggsave(here("figures", "lobsters-line.png"))

## another option:
ggplot(siteyear_summary, aes(x = year, y = median_size_mm)) +
  geom_col() +
  facet_wrap(~site)  

ggsave(here("figures", "lobsters-col.png"))  
  
lobsters %>%
  count(site, year)  

## Learn more about this later:
There are `r count(lobsters)` total lobsters included in this summary.


lobsters_detailed <- lobsters %>%
  mutate(size_m = size_mm / 1000, 
         millenia = 2000,
         observer = "Allison Horst")

lobsters_detailed %>%
  select(date, site, size_m)






